### ISSUE TITLE
about scale consistency problem

### ISSUE THREAD

**Issue by qinzhang2016** [guangmingw/DOPlearning#1]
Hi! Thanks a lot for releasing so useful code. Since it is an unsupervised method, how you deal with the scale problems in depth estimation? I mean that during testing how to ensure that the scale of estimated depth for every mono video be consistent?

**Comment by guangmingw** [comment]
Hi, please refer 
https://github.com/guangmingw/DOPlearning/blob/master/test_disp.py for depth testing. 

The scale of estimated depth is not sure because of the unsupervised method from monocular video. The depth testing uses scale factor determined by GT/prediction ratio, like the SfMlearner: https://github.com/tinghuiz/SfMLearner/blob/master/kitti_eval/eval_depth.py.
