### ISSUE TITLE
 cannot import name 'build_flow_not_intersect' from 'loss_functions_summary'

### ISSUE THREAD

**Issue by TimeLCJ** [guangmingw/DOPlearning#2]
I run train.py according to the tutorial, but the following error is reported：
`Traceback (most recent call last):
  File "/home/lcj/lcj/SLAM/DOPlearning-master/train.py", line 21, in <module>
    from loss_functions_summary import compute_errors, compute_epe, compute_all_epes, flow_diff, spatial_normalize_max, spatial_normalize_mean, new_static_mask, build_flow_not_intersect
ImportError: cannot import name 'build_flow_not_intersect' from 'loss_functions_summary' (/home/lcj/lcj/SLAM/DOPlearning-master/loss_functions_summary.py)`
I checked loss_functions_summary.py, there is no build_flow_not_intersect function here.

**Comment by guangmingw** [comment]
Yes, the build_flow_not_intersect function is not in loss_functions_summary.py, because the function is actually for another project. We had deleted it before uploading the codes. Sorry for that I forgot to delete the import of the function. I have deleted the import now. You can run the codes again.
